/**
 * @file endpoints.ts
 * Typed constants for every Rentman API path defined in OAS v1.7.0.
 * Use these instead of raw strings to get compile-time validation.
 */

export const ENDPOINTS = {
  equipment: '/equipment',
  equipmentSetsContent: '/equipmentsetscontent',
  actualContent: '/actualcontent',
  equipmentAssignedSerials: '/equipmentassignedserials',
  contacts: '/contacts',
  contactPersons: '/contactpersons',
  crew: '/crew',
  crewAvailabilities: '/crewavailability',
  crewRates: '/crewrates',
  projects: '/projects',
  subProjects: '/subprojects',
  projectEquipment: '/projectequipment',
  projectEquipmentGroups: '/projectequipmentgroup',
  projectFunctions: '/projectfunctions',
  projectFunctionGroups: '/projectfunctiongroups',
  projectCrew: '/projectcrew',
  projectVehicles: '/projectvehicles',
  projectRequestEquipment: '/projectrequestequipment',
  invoices: '/invoices',
  invoiceLines: '/invoicelines',
  quotes: '/quotes',
  payments: '/payments',
  appointments: '/appointments',
  appointmentCrew: '/appointmentcrew',
  vehicles: '/vehicles',
  files: '/files',
  fileFolders: '/file_folders',
  folders: '/folders',
  contracts: '/contracts',
  costs: '/costs',
  stockMovements: '/stockmovements',
  stockLocations: '/stocklocations',
  subrentals: '/subrentals',
  subrentalEquipment: '/subrentalequipment',
  subrentalEquipmentGroups: '/subrentalequipmentgroup',
  timeRegistrations: '/timeregistration',
  timeRegistrationActivities: '/timeregistrationactivities',
  leaveMutations: '/leavemutation',
  leaveRequests: '/leaverequest',
  leaveTypes: '/leavetypes',
  repairs: '/repairs',
  serialNumbers: '/serialnumbers',
  accessories: '/accessories',
  rates: '/rates',
  rateFactors: '/ratefactors',
  factorGroups: '/factorgroups',
  factors: '/factors',
  projectTypes: '/projecttypes',
  statuses: '/statuses',
  taxClasses: '/taxclasses',
  ledgerCodes: '/ledgercodes',
  projectRequests: '/projectrequests',
  purchaseOrders: '/purchaseorders',
  purchaseOrderCosts: '/purchaseordercosts',
  purchaseOrderGlobalCosts: '/purchaseorderglobalcosts',
} as const;

/** Union of all valid Rentman API path strings. */
export type RentmanEndpoint = typeof ENDPOINTS[keyof typeof ENDPOINTS];
