/**
 * @file endpoints.ts
 * Typed constants for every Rentman API path defined in OAS v1.7.0.
 * Use these instead of raw strings to get compile-time validation.
 */

export const ENDPOINTS = {
  equipment: '/equipment',
  equipmentSetsContent: '/equipmentsetscontent',
  contacts: '/contacts',
  contactPersons: '/contactpersons',
  crew: '/crew',
  crewAvailabilities: '/crewavailabilities',
  crewRates: '/crewrates',
  projects: '/projects',
  subProjects: '/subprojects',
  projectEquipment: '/projectequipment',
  projectEquipmentGroups: '/projectequipmentgroups',
  projectFunctions: '/projectfunctions',
  projectFunctionGroups: '/projectfunctiongroups',
  projectCrew: '/projectcrew',
  projectVehicles: '/projectvehicles',
  invoices: '/invoices',
  invoiceLines: '/invoicelines',
  invoiceMoments: '/invoicemoments',
  quotes: '/quotes',
  payments: '/payments',
  planning: '/planning',
  activities: '/activities',
  functions: '/functions',
  functionGroups: '/functiongroups',
  taglinks: '/taglinks',
  briefpapier: '/briefpapier',
  numberSeries: '/numberseries',
  templates: '/templates',
  appointments: '/appointments',
  appointmentCrew: '/appointmentcrew',
  vehicles: '/vehicles',
  files: '/files',
  fileFolders: '/filefolders',
  folders: '/folders',
  contracts: '/contracts',
  costs: '/costs',
  stockMovements: '/stockmovements',
  stockLocations: '/stocklocations',
  subrentals: '/subrentals',
  subrentalEquipment: '/subrentalequipment',
  subrentalEquipmentGroups: '/subrentalequipmentgroups',
  timeRegistrations: '/timeregistrations',
  timeRegistrationActivities: '/timeregistrationactivities',
  leaveMutations: '/leavemutations',
  leaveRequests: '/leaverequests',
  leaveTypes: '/leavetypes',
  repairs: '/repairs',
  serialNumbers: '/serialnumbers',
  accessories: '/accessories',
  rates: '/rates',
  factorGroups: '/factorgroups',
  factors: '/factors',
  projectTypes: '/projecttypes',
  statuses: '/statuses',
  taxClasses: '/taxclasses',
  ledgerCodes: '/ledgercodes',
  projectRequests: '/projectrequests',
} as const;

/** Union of all valid Rentman API path strings. */
export type RentmanEndpoint = typeof ENDPOINTS[keyof typeof ENDPOINTS];
